name: Publish Generator

on:
  push:
    branch:
      - main

jobs:
  publish-docs:
    runs-on: debian-trixie
    steps:
      - uses: actions/checkout@v4

      - uses: https://github.com/dtolnay/rust-toolchain@1.85.0
        with:
          target: wasm32-unknown-unknown
          components: rustfmt

      - uses: https://github.com/cargo-bins/cargo-binstall@bc432b49369a3f25c8c8b19578a82060c18a5dd6
        with:
          version: 1.17.6
          
      - name: Install trunk
        run: cargo binstall --locked trunk@0.21.14

      - name: Install wasm-bindgen-cli
        run: cargo binstall wasm-bindgen-cli@0.2.115

      - name: Install JS Deps
        working-directory: cynic-querygen-web/js
        run: npm install

      - name: Build JS
        working-directory: cynic-querygen-web/js
        run: npm run build

      - name: Build Wasm
        working-directory: cynic-querygen-web
        run: trunk build

      - uses: actions/git-pages@v2
        with:
          site: https://generator.cynic-rs.dev
          server: grebedoc.dev
          password: ${{ secrets.GENERATOR_PASSWORD }}
          source: cynic-querygen-web/dist

